name: Python Package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv

    - name: Install dependencies
      run: |
        pipenv install --dev

    - name: Build package
      run: |
        pipenv run python ./src/setup.py sdist bdist_wheel

    - name: Install package
      run: |
        pipenv run pip install dist/*.whl

    - name: Run tests
      run: |        
        pipenv run python tests/test_main.py

    - name: Upload coverage to Coveralls
      if: success()
      uses: coverallsapp/github-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
